# Generated by Django 5.2.6 on 2025-09-19 09:05

import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_chatmessage_sources'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatsession',
            name='appliance',
            field=models.CharField(choices=[('refrigerator', 'Refrigerator'), ('washing-machine', 'Washing Machine')], max_length=50),
        ),
        migrations.AlterField(
            model_name='chatsession',
            name='session_id',
            field=models.CharField(default=uuid.uuid4, max_length=100, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='chatsession',
            unique_together={('user', 'appliance', 'company')},
        ),
    ]
