# Generated by Django 5.2.6 on 2025-09-20 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_alter_chatsession_appliance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatsession',
            name='session_id',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
